### ISSUE TITLE
HTTP Authorization header

### ISSUE THREAD

**Issue by e9gille** [Dyalog/HttpCommand#11]
This is not a bug in HttpCommand, but rather in the server it tries to connect to (I think). HttpCommand sends the AuthType (`basic` in my case) in lowercase which I believe should be ok, but the problem is that the server doesn't recognize it.
Googling the issue I can see others hitting same issue. I suspect many server implementations require the auth-scheme to match case exactly, so expect `Basic` or `Bearer` etc. 

I can work around the issue, but as casing makes no difference to the client, consider changing to use the "expected" casing.

**Comment by bpbecker** [comment]
Addressed in 7d117c4a044d6bcf4558255fc0c236d653697b45

Per RFC7617 the "Basic" authentication scheme name is supposed to be case insensitive. Apparently some servers are more picky...

"Basic" is the only authentication scheme name that HttpCommand will "inject", either if you provide credentials in the URL (for example https://user:pwd@someurl.com), or by setting the <code>Auth</code> configuration setting to a 2-element vector (for example <code>h.Auth←'user' 'pwd'</code>). I have updated HttpCommand to always inject <code>'Basic'</code> versus <code>'basic'</code>.

The authentication scheme can always be set using the <code>AuthType</code> configuration setting and HttpCommand will inject it into the request as typed.
