### ISSUE TITLE
Broken link from Timeout to WaitTime

### ISSUE THREAD

**Issue by abrudz** [Dyalog/HttpCommand#13]
https://dyalog.github.io/HttpCommand/operational-settings/#timeout links to https://dyalog.github.io/HttpCommand/operational-settings/conga-settings.md#waittime but it should be to https://dyalog.github.io/HttpCommand/conga-settings/#waittime

**Comment by bpbecker** [comment]
Fixed in 86dbb82a097babac5cf8aaf0fb211296e36b5415.
I also added some clarification about the use of WaitTime and Timeout settings.
