### ISSUE TITLE
Automatically increase Timeout if needed

### ISSUE THREAD

**Issue by abrudz** [Dyalog/HttpCommand#14]
Since `Timeout` needs to be larger than or equal to `WaitTime÷1000` then HttpCommand should up the `Timeout` if the user increases `WaitTime`. This way, the user only needs to change one value to increase the time given for a response.

**Comment by bpbecker** [comment]
Actually, it doesn't need to be bigger than WaitTime÷1000, it just means that Conga will only have 1 pass through its listening loop.  In that case, the net effect would be as if Timeout was set to WaitTime÷1000.
