### ISSUE TITLE
There is a docs/ folder, but it is not clear what that is for

### ISSUE THREAD

**Issue by aplteam** [Dyalog/HttpCommand#23]
It appears that the folder is not the basis for the documentation, but if that is so, then the documentation appears not to be part of the project which would not be ideal.

Maybe the README should say something about this, and how to contribute to the documentation.

**Comment by bpbecker** [comment]
The docs folder is the basis for the documentation. We use [mkdocs](https://www.mkdocs.org/) to generate the documentation from the docs folder.  The README points to the generated documentation. The mkdocs.yml file describes the configuration for the documentation.
