### ISSUE TITLE
SafeJSON exits early if first character is a codepoint > 127

### ISSUE THREAD

**Issue by e9gille** [Dyalog/HttpCommand#4]
This is probably a bug in the check:
https://github.com/Dyalog/HttpCommand/blob/31d9a947629ce62971bce9a5171644ac920dcfa1/source/HttpCommand.dyalog#L1267

The question is if this is necessary at all. Is UTF-8 encoding not enough?

**Comment by bpbecker** [comment]
Fixed in f5d082e07fbcd752604b5410511afe072c694bef
