### ISSUE TITLE
Should recognize a valid instance of LIB

### ISSUE THREAD

**Issue by e9gille** [Dyalog/HttpCommand#5]
Current check doesn't recognize a valid instance of LIB. Would need to use 
```
¯3.1=CongaRef.⎕NC⊂'Clt'
```
or better yet check the class
```
'.LIB'¯4↑⍕⊃⊃⎕CLASS CongaRef
```

https://github.com/Dyalog/HttpCommand/blob/5dfbd9ceb06ed2a31a129b69b3584813595ed69a/source/HttpCommand.dyalog#L340

**Comment by bpbecker** [comment]
Fixed in 8f462ed6a836116d59e2d467bc3bee794eee8471
