### ISSUE TITLE
Header fields values with multiple %

### ISSUE THREAD

**Issue by cybearinsight** [Dyalog/HttpCommand#53]
If I have a header field where the value contains two % signs then the part between the % signs are removed.

  HttpCommand.Get 'http://localhost:8081'  '' ('klyp' 'klyp%test%kage')

ends up as 
klyp             klypkage 

On the server.
This did not happen in version 5.4.6 but does happen in version 5.6.0

**Comment by bpbecker** [comment]
Addressed in v5.7.0

- New setting HeaderSubstitution controls how environment variables may be referenced.  The default is '' which disables substitution
- The substitution logic, if enabled, checks that the environment variable actually exists and does no substitution if it does not exist.
