### ISSUE TITLE
HttpCommand creates an Error in GetJson in case it cannot find the Conga DLLs

### ISSUE THREAD

**Issue by aplteam** [Dyalog/HttpCommand#55]
This line in GetJson:
```
(r.HttpMessage,' (',(⍕r.HttpStatus),')')Assert r.HttpStatus=200
```
crashes because
```
      r.HttpStatus≡⍬
1
```

I am on the very latest version published as a Tatin package.

(This is my <02211>)

**Comment by aplteam** [comment]
As a side note, `dyalogRoot` is in a Runtime application the folder the EXE was loaded from.
That would not work unless one copies the Conga WS into a sub-folder "was" of that folder.

(Not an issue if the Conga namespace is part of the RunTime APP)

**Comment by plusdottimes** [comment]
> This line in GetJson:
> 
> ```
> (r.HttpMessage,' (',(⍕r.HttpStatus),')')Assert r.HttpStatus=200
> ```
> 
> crashes because
> 
> ```
>       r.HttpStatus≡⍬
> 1
> ```
> 
> I am on the very latest version published as a Tatin package.
> 
> (This is my <02211>)

To provide context for other readers of this issue:

`GetJson` is your function and not a part of `HttpCommand` and not to be confused with `HttpCommand.GetJSON`.

`r.HttpStatus` will be `⍬` in the event that HttpCommand couldn't send the request or receive the response from the host.  In this case `r.rc` would be non-0 and `r.msg` should contain some indication about what went wrong.  You should check `r.rc` before checking `r.HttpStatus` or use [`r.IsOK`](https://dyalog.github.io/HttpCommand/5.8/result-operational/#isok).

**Comment by bpbecker** [comment]
To provide some context for other readers of this issue:

`GetJson` is your function and not a part of `HttpCommand` and not to be confused with `HttpCommand.GetJSON`.

`r.HttpStatus` will be empty if `HttpCommand` was unable to send the request to or receive a response from the host. This means we don't have any HTTP status information from the host.  In that case `r.rc` should be non-0 and `r.msg` should contain information about the failure.  So, you should check `r.rc` before checking `r.HttpStatus` or use [`r.IsOK`](https://dyalog.github.io/HttpCommand/5.8/result-operational/#isok).

As to needing the conga workspace to be co-located with the Dyalog runtime executable - that's how any runtime application would need to be configured if `Conga` namespace is being copied into the application workspace.  As you noted, if the `Conga` namespace is already present in the application workspace then you don't need the conga workspace, but the Conga shared libraries should be co-located with the Dyalog runtime executable.
