### ISSUE TITLE
819⌶ <==> ⎕C

### ISSUE THREAD

**Issue by aplteam** [Dyalog/HttpCommand#56]
HttpCommand is not ready for 20.0 yet.

**Comment by bpbecker** [comment]
HttpCommand has dealt with 819⌶ being removed since v5.3.3 on 14 Aug 2023.
819⌶ remains in the code as a fallback in case you're using a Dyalog version that predates ⎕C.
But for versions that do support ⎕C, 819⌶ is never called.

**Comment by aplteam** [comment]
Ah, I relied on a crude search for 819 in all source code files, sorry.

**Comment by bpbecker** [comment]
No worries :) Happens to us all.
