### ISSUE TITLE
Unexpected INDEX ERROR at GetHeader[]

### ISSUE THREAD

**Issue by e9gille** [Dyalog/HttpCommand#6]
This is caused by the Result space being created in the root and therefore inherits ⎕IO ⎕ML from it. GetHeader assumes ⎕IO=1 and ⎕ML=1.

https://github.com/Dyalog/HttpCommand/blob/5dfbd9ceb06ed2a31a129b69b3584813595ed69a/source/HttpCommand.dyalog#L87

**Comment by bpbecker** [comment]
Fixed in 6955fcbad22e2eb4d0c9e5b49780cd248555d0b0
